# Generated by Django 4.2 on 2025-02-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='height_cm',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
